const PREPOSITION_USAGE_PROFILES = [
  {
    "base": "di",
    "id": "di_possesso",
    "title": "الملكية والتخصيص",
    "meaning": "لـ / الخاص بـ",
    "description": "يربط الشيء بمالكه أو بما يخصه.",
    "form": "di",
    "it": "Il telefono di Leo è nuovo",
    "ar": "تليفون ليو جديد",
    "en": "Leo’s phone is new",
    "color": "#e53935",
    "grammarId": "prep_di"
  },
  {
    "base": "di",
    "id": "di_origine",
    "title": "الأصل والمنشأ",
    "meaning": "من",
    "description": "مع المدن والأصل، ويأتي كثيرًا مع essere.",
    "form": "di",
    "it": "Sono di Roma",
    "ar": "أنا من روما",
    "en": "I am from Rome",
    "color": "#1e88e5",
    "grammarId": "prep_di"
  },
  {
    "base": "di",
    "id": "di_materiale",
    "title": "المادة المصنوع منها",
    "meaning": "من",
    "description": "يبين المادة التي صُنع منها الشيء.",
    "form": "di",
    "it": "Il tavolo è di legno",
    "ar": "الطاولة من الخشب",
    "en": "The table is made of wood",
    "color": "#8e24aa",
    "grammarId": "prep_di"
  },
  {
    "base": "di",
    "id": "di_argomento",
    "title": "الموضوع",
    "meaning": "عن",
    "description": "مع الكلام والكتابة والحديث عن موضوع.",
    "form": "di",
    "it": "Parliamo di calcio",
    "ar": "نتحدث عن كرة القدم",
    "en": "We talk about football",
    "color": "#00897b",
    "grammarId": "prep_di"
  },
  {
    "base": "di",
    "id": "di_contenuto",
    "title": "المحتوى أو النوع",
    "meaning": "في / عن",
    "description": "يحدد محتوى كتاب أو نوع شيء.",
    "form": "di",
    "it": "Leggo un libro di storia",
    "ar": "أقرأ كتاب تاريخ",
    "en": "I read a history book",
    "color": "#fb8c00",
    "grammarId": "prep_di"
  },
  {
    "base": "di",
    "id": "di_tempo",
    "title": "التعبير الزمني",
    "meaning": "في / أثناء",
    "description": "يستخدم مع أجزاء اليوم مثل di notte وdi giorno.",
    "form": "di",
    "it": "Studio di notte",
    "ar": "أذاكر في الليل",
    "en": "I study at night",
    "color": "#43a047",
    "grammarId": "prep_di"
  },
  {
    "base": "di",
    "id": "di_quantita",
    "title": "الكمية أو الجزء",
    "meaning": "من",
    "description": "يأتي بعد كلمات الكمية أو الأوعية.",
    "form": "di",
    "it": "Bevo una tazza di caffè",
    "ar": "أشرب فنجانًا من القهوة",
    "en": "I drink a cup of coffee",
    "color": "#d81b60",
    "grammarId": "prep_di"
  },
  {
    "base": "di",
    "id": "di_causa",
    "title": "السبب",
    "meaning": "من / بسبب",
    "description": "يعبّر عن سبب شعور أو حالة.",
    "form": "di",
    "it": "Tremo di freddo",
    "ar": "أرتجف من البرد",
    "en": "I shiver from the cold",
    "color": "#5e35b1",
    "grammarId": "prep_di"
  },
  {
    "base": "di",
    "id": "di_modo",
    "title": "الكيفية",
    "meaning": "بـ / على نحو",
    "description": "يظهر في تعبيرات ثابتة تصف طريقة الفعل.",
    "form": "di",
    "it": "Cammino di corsa",
    "ar": "أمشي مسرعًا",
    "en": "I walk in a hurry",
    "color": "#00acc1",
    "grammarId": "prep_di"
  },
  {
    "base": "di",
    "id": "di_infinito",
    "title": "تكملة الفعل بالمصدر",
    "meaning": "أن / بـ",
    "description": "بعض الأفعال تحتاج di قبل المصدر.",
    "form": "di",
    "it": "Ho deciso di partire",
    "ar": "قررت أن أغادر",
    "en": "I decided to leave",
    "color": "#6d4c41",
    "grammarId": "prep_di"
  },
  {
    "base": "a",
    "id": "a_direzione",
    "title": "الاتجاه إلى مدينة أو مكان",
    "meaning": "إلى",
    "description": "يستخدم للحركة نحو مدينة أو مكان محدد.",
    "form": "a",
    "it": "Vado a Milano",
    "ar": "أذهب إلى ميلانو",
    "en": "I go to Milan",
    "color": "#e53935",
    "grammarId": "prep_a"
  },
  {
    "base": "a",
    "id": "a_stato",
    "title": "المكان مع مدينة",
    "meaning": "في",
    "description": "يستخدم للإقامة أو الوجود في مدينة.",
    "form": "a",
    "it": "Vivo a Roma",
    "ar": "أعيش في روما",
    "en": "I live in Rome",
    "color": "#1e88e5",
    "grammarId": "prep_a"
  },
  {
    "base": "a",
    "id": "a_ora",
    "title": "الوقت والساعة",
    "meaning": "في تمام",
    "description": "يحدد الساعة أو لحظة زمنية دقيقة.",
    "form": "alle",
    "it": "Arrivo alle tre",
    "ar": "أصل في تمام الثالثة",
    "en": "I arrive at three",
    "color": "#8e24aa",
    "grammarId": "prep_a"
  },
  {
    "base": "a",
    "id": "a_modo",
    "title": "الطريقة",
    "meaning": "بـ / على",
    "description": "يصف طريقة الحركة أو أداء الفعل.",
    "form": "a",
    "it": "Vado a piedi",
    "ar": "أذهب مشيًا",
    "en": "I go on foot",
    "color": "#00897b",
    "grammarId": "prep_a"
  },
  {
    "base": "a",
    "id": "a_strumento",
    "title": "الأداة في تعبير ثابت",
    "meaning": "بـ",
    "description": "يستخدم في بعض تعبيرات الوسيلة والأداة.",
    "form": "a",
    "it": "Chiudo la porta a chiave",
    "ar": "أغلق الباب بالمفتاح",
    "en": "I lock the door with a key",
    "color": "#fb8c00",
    "grammarId": "prep_a"
  },
  {
    "base": "a",
    "id": "a_indiretto",
    "title": "المفعول غير المباشر",
    "meaning": "لـ / إلى",
    "description": "يوصل الفعل بالشخص المتلقي.",
    "form": "a",
    "it": "Telefono a Marco",
    "ar": "أتصل بماركو",
    "en": "I call Marco",
    "color": "#43a047",
    "grammarId": "prep_a"
  },
  {
    "base": "a",
    "id": "a_frequenza",
    "title": "المعدل والتكرار",
    "meaning": "في كل",
    "description": "يعبّر عن معدل التكرار.",
    "form": "al",
    "it": "Prendo la medicina due volte al giorno",
    "ar": "آخذ الدواء مرتين في اليوم",
    "en": "I take the medicine twice a day",
    "color": "#d81b60",
    "grammarId": "prep_a"
  },
  {
    "base": "da",
    "id": "da_tempo",
    "title": "بداية زمن مستمر",
    "meaning": "منذ",
    "description": "مع مدة بدأت في الماضي وما زالت مستمرة.",
    "form": "da",
    "it": "Vivo qui da due anni",
    "ar": "أعيش هنا منذ سنتين",
    "en": "I have lived here for two years",
    "color": "#5e35b1",
    "grammarId": "prep_da"
  },
  {
    "base": "da",
    "id": "da_origine",
    "title": "القدوم أو الحركة من مصدر",
    "meaning": "من",
    "description": "يبين نقطة الانطلاق أو المصدر.",
    "form": "da",
    "it": "Vengo da Roma",
    "ar": "أنا قادم من روما",
    "en": "I come from Rome",
    "color": "#00acc1",
    "grammarId": "prep_da"
  },
  {
    "base": "da",
    "id": "da_persona",
    "title": "الذهاب عند شخص",
    "meaning": "عند / إلى",
    "description": "يستخدم للذهاب إلى منزل أو مكان شخص أو مهني.",
    "form": "da",
    "it": "Vado da Marco",
    "ar": "أذهب عند ماركو",
    "en": "I go to Marco’s place",
    "color": "#6d4c41",
    "grammarId": "prep_da"
  },
  {
    "base": "da",
    "id": "da_agente",
    "title": "الفاعل في المبني للمجهول",
    "meaning": "من / بواسطة",
    "description": "يبين من قام بالفعل في الجملة المبنية للمجهول.",
    "form": "da",
    "it": "Il libro è scritto da Maria",
    "ar": "الكتاب مكتوب بواسطة ماريا",
    "en": "The book is written by Maria",
    "color": "#e53935",
    "grammarId": "prep_da"
  },
  {
    "base": "da",
    "id": "da_scopo",
    "title": "الغرض أو الاستخدام",
    "meaning": "لـ",
    "description": "يصف وظيفة الشيء أو الغرض منه.",
    "form": "da",
    "it": "Uso gli occhiali da sole",
    "ar": "أستخدم نظارات الشمس",
    "en": "I use sunglasses",
    "color": "#1e88e5",
    "grammarId": "prep_da"
  },
  {
    "base": "da",
    "id": "da_caratteristica",
    "title": "الصفة أو الميزة",
    "meaning": "ذو / ذات",
    "description": "يصف سمة مميزة، وغالبًا يأتي مركبًا مع أداة تعريف.",
    "form": "dai",
    "it": "È una ragazza dai capelli neri",
    "ar": "هي فتاة ذات شعر أسود",
    "en": "She is a girl with black hair",
    "color": "#8e24aa",
    "grammarId": "prep_da"
  },
  {
    "base": "da",
    "id": "da_fare",
    "title": "شيء مطلوب فعله",
    "meaning": "يجب / قابل لـ",
    "description": "يأتي مع المصدر ليعني شيئًا يجب فعله.",
    "form": "da",
    "it": "Ho molto da fare",
    "ar": "عندي الكثير لأفعله",
    "en": "I have a lot to do",
    "color": "#00897b",
    "grammarId": "prep_da"
  },
  {
    "base": "in",
    "id": "in_luogo",
    "title": "مكان داخلي أو محدود",
    "meaning": "في",
    "description": "للوجود داخل غرفة أو مؤسسة أو مكان مغلق.",
    "form": "in",
    "it": "Sono in cucina",
    "ar": "أنا في المطبخ",
    "en": "I am in the kitchen",
    "color": "#fb8c00",
    "grammarId": "prep_in"
  },
  {
    "base": "in",
    "id": "in_paese",
    "title": "الإقامة في دولة أو منطقة",
    "meaning": "في",
    "description": "مع الدول والقارات والمناطق.",
    "form": "in",
    "it": "Vivo in Italia",
    "ar": "أعيش في إيطاليا",
    "en": "I live in Italy",
    "color": "#43a047",
    "grammarId": "prep_in"
  },
  {
    "base": "in",
    "id": "in_direzione",
    "title": "الاتجاه إلى دولة أو منطقة",
    "meaning": "إلى",
    "description": "للسفر إلى دولة أو قارة أو منطقة.",
    "form": "in",
    "it": "Vado in Italia",
    "ar": "أذهب إلى إيطاليا",
    "en": "I go to Italy",
    "color": "#d81b60",
    "grammarId": "prep_in"
  },
  {
    "base": "in",
    "id": "in_trasporto",
    "title": "وسيلة المواصلات",
    "meaning": "بـ",
    "description": "مع وسائل النقل غالبًا بدون أداة تعريف.",
    "form": "in",
    "it": "Viaggio in treno",
    "ar": "أسافر بالقطار",
    "en": "I travel by train",
    "color": "#5e35b1",
    "grammarId": "prep_in"
  },
  {
    "base": "in",
    "id": "in_tempo",
    "title": "الفترة أو الفصل",
    "meaning": "في",
    "description": "مع الفصول والسنوات والفترات العامة.",
    "form": "in",
    "it": "Parto in estate",
    "ar": "أسافر في الصيف",
    "en": "I leave in summer",
    "color": "#00acc1",
    "grammarId": "prep_in"
  },
  {
    "base": "in",
    "id": "in_modo",
    "title": "الكيفية أو الحالة",
    "meaning": "بـ / في حالة",
    "description": "يصف الطريقة أو الحالة التي يتم بها الفعل.",
    "form": "in",
    "it": "Lavoro in silenzio",
    "ar": "أعمل في صمت",
    "en": "I work in silence",
    "color": "#6d4c41",
    "grammarId": "prep_in"
  },
  {
    "base": "in",
    "id": "in_durata",
    "title": "المدة اللازمة للإنجاز",
    "meaning": "خلال",
    "description": "يحدد الوقت المطلوب لإتمام شيء.",
    "form": "in",
    "it": "Finisco in due ore",
    "ar": "أنتهي خلال ساعتين",
    "en": "I finish in two hours",
    "color": "#e53935",
    "grammarId": "prep_in"
  },
  {
    "base": "con",
    "id": "con_compagnia",
    "title": "المصاحبة",
    "meaning": "مع",
    "description": "مرافقة شخص أو حيوان.",
    "form": "con",
    "it": "Passeggio con Marco",
    "ar": "أتمشى مع ماركو",
    "en": "I walk with Marco",
    "color": "#1e88e5",
    "grammarId": "prep_con"
  },
  {
    "base": "con",
    "id": "con_strumento",
    "title": "الأداة أو الوسيلة",
    "meaning": "بـ / باستخدام",
    "description": "يحدد الأداة المستعملة لعمل الفعل.",
    "form": "con",
    "it": "Scrivo con la penna",
    "ar": "أكتب بالقلم",
    "en": "I write with a pen",
    "color": "#8e24aa",
    "grammarId": "prep_con"
  },
  {
    "base": "con",
    "id": "con_modo",
    "title": "الكيفية",
    "meaning": "بـ / مع",
    "description": "يصف الطريقة التي حدث بها الفعل.",
    "form": "con",
    "it": "Parlo con gentilezza",
    "ar": "أتحدث بلطف",
    "en": "I speak kindly",
    "color": "#00897b",
    "grammarId": "prep_con"
  },
  {
    "base": "con",
    "id": "con_qualita",
    "title": "الصفة أو الميزة",
    "meaning": "ذو / ذات",
    "description": "يضيف صفة أو ميزة إلى اسم.",
    "form": "con",
    "it": "È una ragazza con i capelli neri",
    "ar": "هي فتاة ذات شعر أسود",
    "en": "She is a girl with black hair",
    "color": "#fb8c00",
    "grammarId": "prep_con"
  },
  {
    "base": "con",
    "id": "con_circostanza",
    "title": "الظرف أو الحالة المصاحبة",
    "meaning": "مع / في ظل",
    "description": "يبين ظرفًا مصاحبًا للحدث.",
    "form": "con",
    "it": "Con la pioggia, resto a casa",
    "ar": "مع المطر أبقى في المنزل",
    "en": "With the rain, I stay home",
    "color": "#43a047",
    "grammarId": "prep_con"
  },
  {
    "base": "su",
    "id": "su_superficie",
    "title": "على سطح",
    "meaning": "على",
    "description": "يحدد وجود شيء فوق سطح.",
    "form": "sul",
    "it": "Il libro è sul tavolo",
    "ar": "الكتاب على الطاولة",
    "en": "The book is on the table",
    "color": "#d81b60",
    "grammarId": "prep_su"
  },
  {
    "base": "su",
    "id": "su_argomento",
    "title": "الموضوع",
    "meaning": "عن",
    "description": "يحدد موضوع كتاب أو حديث.",
    "form": "su",
    "it": "Leggo un libro su Roma",
    "ar": "أقرأ كتابًا عن روما",
    "en": "I read a book about Rome",
    "color": "#5e35b1",
    "grammarId": "prep_su"
  },
  {
    "base": "su",
    "id": "su_approssimazione",
    "title": "التقريب",
    "meaning": "حوالي",
    "description": "يعبّر عن رقم أو كمية تقريبية.",
    "form": "sui",
    "it": "Costa sui venti euro",
    "ar": "سعره حوالي عشرين يورو",
    "en": "It costs about twenty euros",
    "color": "#00acc1",
    "grammarId": "prep_su"
  },
  {
    "base": "su",
    "id": "su_rapporto",
    "title": "النسبة",
    "meaning": "من أصل",
    "description": "يعبّر عن نسبة جزء إلى مجموع.",
    "form": "su",
    "it": "Tre studenti su dieci hanno risposto",
    "ar": "ثلاثة طلاب من أصل عشرة أجابوا",
    "en": "Three students out of ten answered",
    "color": "#6d4c41",
    "grammarId": "prep_su"
  },
  {
    "base": "su",
    "id": "su_base",
    "title": "الأساس أو الاعتماد",
    "meaning": "بناءً على",
    "description": "يبين الأساس الذي بُني عليه القرار.",
    "form": "sulla",
    "it": "Ho deciso sulla base dei dati",
    "ar": "قررت بناءً على البيانات",
    "en": "I decided based on the data",
    "color": "#e53935",
    "grammarId": "prep_su"
  },
  {
    "base": "per",
    "id": "per_scopo",
    "title": "الغرض والهدف",
    "meaning": "لكي / من أجل",
    "description": "يبين الهدف من الفعل.",
    "form": "per",
    "it": "Studio per imparare",
    "ar": "أذاكر لكي أتعلم",
    "en": "I study to learn",
    "color": "#1e88e5",
    "grammarId": "prep_per"
  },
  {
    "base": "per",
    "id": "per_destinatario",
    "title": "المتلقي أو المستفيد",
    "meaning": "لـ",
    "description": "يبين الشخص الذي خُصص له الشيء.",
    "form": "per",
    "it": "Questo regalo è per te",
    "ar": "هذه الهدية لك",
    "en": "This gift is for you",
    "color": "#8e24aa",
    "grammarId": "prep_per"
  },
  {
    "base": "per",
    "id": "per_durata",
    "title": "المدة",
    "meaning": "لمدة",
    "description": "يحدد طول مدة الحدث.",
    "form": "per",
    "it": "Ho lavorato per due ore",
    "ar": "عملت لمدة ساعتين",
    "en": "I worked for two hours",
    "color": "#00897b",
    "grammarId": "prep_per"
  },
  {
    "base": "per",
    "id": "per_percorso",
    "title": "المرور أو الطريق",
    "meaning": "عبر / عن طريق",
    "description": "يبين المكان الذي نمر به.",
    "form": "per",
    "it": "Passo per Roma",
    "ar": "أمر عبر روما",
    "en": "I pass through Rome",
    "color": "#fb8c00",
    "grammarId": "prep_per"
  },
  {
    "base": "per",
    "id": "per_causa",
    "title": "السبب",
    "meaning": "بسبب / من",
    "description": "يبين سبب شعور أو حدث.",
    "form": "per",
    "it": "Tremo per la paura",
    "ar": "أرتجف من الخوف",
    "en": "I tremble with fear",
    "color": "#43a047",
    "grammarId": "prep_per"
  },
  {
    "base": "per",
    "id": "per_mezzo",
    "title": "الوسيلة أو القناة",
    "meaning": "عن طريق",
    "description": "يبين وسيلة الإرسال أو الاتصال.",
    "form": "per",
    "it": "Ti mando il file per e-mail",
    "ar": "أرسل لك الملف عبر البريد الإلكتروني",
    "en": "I send you the file by email",
    "color": "#d81b60",
    "grammarId": "prep_per"
  },
  {
    "base": "tra_fra",
    "id": "tra_spazio",
    "title": "بين أو وسط",
    "meaning": "بين",
    "description": "للمكان أو الوجود ضمن مجموعة.",
    "form": "tra",
    "it": "Sono tra amici",
    "ar": "أنا بين أصدقاء",
    "en": "I am among friends",
    "color": "#5e35b1",
    "grammarId": "prep_tra_fra"
  },
  {
    "base": "tra_fra",
    "id": "fra_tempo",
    "title": "وقت في المستقبل",
    "meaning": "بعد",
    "description": "يبين المدة الباقية قبل حدث مستقبلي.",
    "form": "fra",
    "it": "Parto fra due giorni",
    "ar": "أسافر بعد يومين",
    "en": "I leave in two days",
    "color": "#00acc1",
    "grammarId": "prep_tra_fra"
  },
  {
    "base": "tra_fra",
    "id": "tra_relazione",
    "title": "العلاقة",
    "meaning": "بين",
    "description": "يبين علاقة متبادلة.",
    "form": "tra",
    "it": "C’è fiducia tra noi",
    "ar": "هناك ثقة بيننا",
    "en": "There is trust between us",
    "color": "#6d4c41",
    "grammarId": "prep_tra_fra"
  },
  {
    "base": "tra_fra",
    "id": "tra_scelta",
    "title": "الاختيار",
    "meaning": "بين",
    "description": "يستخدم عند الاختيار من بدائل.",
    "form": "tra",
    "it": "Scegli tra questo e quello",
    "ar": "اختر بين هذا وذاك",
    "en": "Choose between this and that",
    "color": "#e53935",
    "grammarId": "prep_tra_fra"
  }
];
